# Generated by Django 5.0.6 on 2024-05-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('connection', 'connection'), ('problem', 'problem')], max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('photo_ID', models.ImageField(upload_to='photo_id/')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_modem', models.ImageField(upload_to='internet/')),
                ('modem_SN', models.CharField(max_length=100)),
                ('optical_cable', models.CharField(max_length=100)),
                ('fastconnector', models.CharField(max_length=100)),
                ('siqnal', models.CharField(max_length=100)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internet', to='services.task')),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_modem', models.ImageField(upload_to='tv/')),
                ('modem_SN', models.CharField(max_length=100)),
                ('rg6_cable', models.CharField(max_length=100)),
                ('f_connector', models.CharField(max_length=100)),
                ('splitter', models.CharField(max_length=100)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tv', to='services.task')),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_modem', models.ImageField(upload_to='voice/')),
                ('modem_SN', models.CharField(max_length=100)),
                ('home_number', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='services.task')),
            ],
        ),
    ]
