# Generated by Django 5.0.6 on 2024-05-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('photo_ID', models.ImageField(upload_to='documents/')),
                ('location', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('Internet', 'Internet'), ('TV', 'TV'), ('Voice', 'Voice')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Internet', 'Internet'), ('TV', 'TV'), ('Voice', 'Voice')], max_length=100)),
                ('photo_modem', models.ImageField(upload_to='documents/')),
                ('modem_SN', models.CharField(max_length=100)),
                ('optical_cable', models.CharField(max_length=100)),
                ('fastconnector', models.CharField(max_length=100)),
                ('siqnal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Internet', 'Internet'), ('TV', 'TV'), ('Voice', 'Voice')], max_length=100)),
                ('photo_modem', models.ImageField(upload_to='documents/')),
                ('modem_SN', models.CharField(max_length=100)),
                ('rg6_cable', models.CharField(max_length=100)),
                ('f_connector', models.CharField(max_length=100)),
                ('splitter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Internet', 'Internet'), ('TV', 'TV'), ('Voice', 'Voice')], max_length=100)),
                ('photo_modem', models.ImageField(upload_to='documents/')),
                ('modem_SN', models.CharField(max_length=100)),
                ('home_number', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
