# Generated by Django 5.0.6 on 2024-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Internet', 'Internet'), ('TV', 'TV'), ('Voice', 'Voice')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='connectionsurvey',
            name='service_type',
        ),
        migrations.AddField(
            model_name='connectionsurvey',
            name='service_type',
            field=models.ManyToManyField(to='services.servicetype'),
        ),
    ]
