# Generated by Django 5.0.6 on 2024-05-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicetype_remove_connectionsurvey_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionsurvey',
            name='service_type',
            field=models.ManyToManyField(choices=[('Internet', 'Internet'), ('TV', 'TV'), ('Voice', 'Voice')], to='services.servicetype'),
        ),
    ]
