# Generated by Django 5.0.6 on 2024-05-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_connectionsurvey_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionsurvey',
            name='service_type',
            field=models.ManyToManyField(to='services.servicetype'),
        ),
    ]
